source:
  jenkins:
    url: $JENKINS_URL
    job_name: Metrics Web
    username: vova.beloded@solid.software
    api_key: $JENKINS_API_KEY
destination:
  firestore:
    firebase_project_id: metrics-test-25d15
    firebase_user_email: $WEB_APP_USER_EMAIL
    firebase_user_pass: $WEB_APP_USER_PASSWORD
    firebase_public_api_key: $CI_INTEGRATIONS_FIREBASE_API_KEY
    metrics_project_id: metrics_web_jenkins
