name: Slack Action Tests

on:
  push:
    branches: master

jobs:
  build-something:
    name: Build some project
    runs-on: ubuntu-latest
    steps:
      - name: Build something
        run: exit(1)

  send-notification:
    name: Send notification
    runs-on: ubuntu-latest
    needs: [ build-something ]
    if: ${{ failure() }}
    steps:
      - name: Send notification
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          repository: solid-vovabeloded/monorepo
          event-type: send_slack_notification
          client-payload: '{"workflow_name": "$GITHUB_WORKFLOW", "run_url": "https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"}'
