name: Slack Action Tests

on:
  push:
    branches: master

jobs:
  build-something:
    name: Build some project
    runs-on: ubuntu-latest
    steps:
      - name: Build something
        run: exit(1)

  notify-slack:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    needs: build-something
    if: ${{ failure() }}
    steps:
      - name: Send Notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CUSTOM_PAYLOAD: '"text": {"type": "mrkdwn", "text": "A `test message` with a markdown from a fork [repository](https://github.com/solid-vovabeloded/monorepo/actions/runs/427896116)"}'
        uses: Ilshidur/action-slack@2.0.2
