name: Slack Action Tests

on:
  push:
    branches: master

jobs:
  build-something:
    name: Build some project
    runs-on: ubuntu-latest
    steps:
      - name: Build something
        run: exit(1)

  notify-slack:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    needs: build-something
    if: ${{ failure() }}
    steps:
      - name: Send Notification
        run: echo "sending slack notification ..."