name: Slack Action Tests

on:
  push:
    branches: master

jobs:
  build-something:
    name: Build some project
    runs-on: ubuntu-latest
    steps:
      - name: Build something
        run: exit(1)

  send-notification:
    name: Send notification
    runs-on: ubuntu-latest
    needs: [ build-something ]
    if: ${{ always() }}
    steps:
      - name: Send notification to Slack
        if: needs.build-something.result == 'failure'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          repository: solid-vovabeloded/monorepo
          event-type: send_slack_notification
          client-payload: '{"workflow_name": "${{ github.workflow }}", "run_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
