name: Slack Notifications

on:
  repository_dispatch:
    types: [ send_slack_notification ]

jobs:
  send_slack_notification:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    needs: build-something
    if: ${{ failure() }}
    steps:
      - name: Send Notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CUSTOM_PAYLOAD: '{
                                    "type":"mrkdwn",
                                    "text":"Oops! The ${{ github.event.client_payload.workflow_name }} run failed. See details <${{ github.event.client_payload.run_url }}|here>"
                                 }'
        uses: Ilshidur/action-slack@2.0.2